[general]
live_config_reload = true

[bell]
animation = "Ease"
color = "#ffffff"
duration = 150

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "#ff9e64"
index = 16

[[colors.indexed_colors]]
color = "#db4b4b"
index = 17

[colors.bright]
black = "#414868"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[colors.normal]
black = "#1D202F"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#a9b1d6"
yellow = "#e0af68"

[colors.primary]
background = "#24283b"
foreground = "#c0caf5"

[cursor]
style.shape = "Block"
style.blinking = "Never"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 10.0

[font.bold]
family = "CascadiaCode"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "CascadiaCode"
style = "Italic"

[font.normal]
family = "CascadiaCode"
style = "Normal"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "fzf \r"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001b"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b"
key = "J"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001b"
key = "A"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001b"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
key = "N"
mods = "Alt"

[keyboard.bindings.command]
args = []
program = "alacritty"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 30

[window.padding]
x = 2
y = 2
